#!/usr/bin/env bash

# 获取最新的 Git 标签
latest_tag=$(git tag --sort=committerdate | grep -E '^github-v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
if [ -z "$latest_tag" ]; then
    echo "未找到标签"
    exit 1
fi
echo "最新标签: $latest_tag"

# 更新 latest 标签
git tag -d latest
git push origin :refs/tags/latest
git tag -a latest $latest_tag -m "更新 latest 到 $latest_tag"
git push origin latest
