#!/usr/bin/env bash

# 解析命令行参数
minor=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    --minor) minor=true; shift 1;;
    *) echo "未知参数: $1"; exit 1;;
  esac
done

# 获取最新的 Git 标签
git fetch --force --tags
latest_tag=$(git tag --sort=committerdate | grep -E '^github-v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
if [ -z "$latest_tag" ]; then
    echo "未找到标签"
    exit 1
fi

echo "最新标签: $latest_tag"

# 将标签分割为 major、minor 和 patch 版本号
IFS='.' read -ra VERSION <<< "$latest_tag"

if [ "$minor" = true ]; then
    # 增加 minor 版本号并重置 patch 为 0
    minor_number=${VERSION[1]}
    let "minor_number++"
    new_version="${VERSION[0]}.$minor_number.0"
else
    # 增加 patch 版本号
    patch_number=${VERSION[2]}
    let "patch_number++"
    new_version="${VERSION[0]}.${VERSION[1]}.$patch_number"
fi

echo "新版本: $new_version"

# 打标签
git tag $new_version
git push --tags
